language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=abcl

  matrix:
    allow_failures:
      - env: LISP=abcl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl --load runtest.lisp
